### ISSUE TITLE
Verify that all variables are tested with Probtest

### ISSUE THREAD

**Issue by MeraX** [MeteoSwiss/probtest#7]
Currently, Probtest validates only those variables and file_ids that are in the ref as well as in the cur. If a variable is missing in either of them, the variable is silently ignored. This could result in a case where no variable is validated at all. A check should be added that makes sure that there are the sets of variables in cur as in ref are the same.

**Comment by AnnikaLau** [comment]
This has actually been solved with the MR: [Consolidate probtest](https://github.com/MeteoSwiss/probtest/pull/20)

_- Probtest now fails when there is no overlap between the variables in the reference and the test file. It gives a warning when are there variables which are not in both the reference and the test case. It also specifies which variables those are._
